CREATE TABLE Request (
TBR_REQUEST_TITLE varchar(255),
TBR_SOURCE_REQUEST varchar(255),
TBR_INSTITUTE_DESC varchar(255),
TBR_DEPT_DESC varchar(255),
TBR_REQUESTER_DESC varchar(255),
TBR_REQUEST_DT timestamp NULL DEFAULT NULL,
TBR_ILAB_NO varchar(255),
TBR_FINALIZE_FLAG varchar(255),
TBR_COST_CENTER bigint(20),
TBR_FUND_ID bigint(20),
TBR_MTA_FLAG varchar(255),
TBR_DISTRIBUTION_OPTION_DESC varchar(255),
TBR_HBC_ID varchar(255),
TBR_HBC_COMMITTEE_APPROVAL_DT timestamp NULL DEFAULT NULL,
TBR_MIN_UNIT bigint(20),
TBR_MTA_APPROVAL_DT timestamp NULL DEFAULT NULL,
TBR_PICKUP_ARRANGEMENT_DESC text,
TBR_PROSPECT_FLAG varchar(255),
TBR_TYPE_DESC varchar(255),
TBR_RESTROSPECT_FLAG varchar(255),
TBR_SPECIMEN_COLLECTION_METHOD text,
TBR_COMMENTS varchar(255),
TBR_CONTACT_NAME varchar(255),
TBR_SPECIMEN_USAGE_DESC text,
TBR_WAIVER_NO varchar(255),
TBR_MIN_SIZE_DESC varchar(255),
TBR_STS_DESC varchar(255),
TBR_SPECIAL_HANDLING_DESC varchar(255)
);

CREATE TABLE Distribution_Requirement(
TBRD_SPECIMEN_TYPE_CD varchar(255),
TBRD_SITE_DESC varchar(255),
TBRD_SUB_SITE_DESC varchar(255),
TBRD_SUB2_SITE_DESC varchar(255),
TBRD_CATEGORY_DESC varchar(255),
TBRD_EXPECTED_AMT decimal(19,6),
TBRD_BILLING_AMT decimal(19,6),
TBRD_SOURCE_REQUEST varchar(255),
TBRD_HISTOLOGY_DESC varchar(255),
TBRD_HISTOLOGY_SUB_DESC varchar(255),
TBRD_HISTOLOGY_SUB2_DESC varchar(255),
TBRD_HISTOLOGY_SUB3_DESC varchar(255),
TBRD_QUALITY_DESC varchar(255),
TBRD_UNIT_DESC varchar(255),
TBRD_NOTES text
);

CREATE TABLE Distribution_Order (
TBDS_SPECIMEN_REQUEST_ID varchar(255),
TBDS_DISTRIBUTION_DT timestamp NULL DEFAULT NULL,
TBDS_SOURCE_REQUEST varchar(255),
TBDS_BILLING_AMT decimal(19,6),
SPECIMEN_LABEL varchar(255),
TBDS_BILLING_DT timestamp NULL DEFAULT NULL
);

